name: gg_fake_stopwatch
description: A stopwatch that is in sync with FakeAsync.elapsed. Use this stopwatch in tests using fakeAsync.
version: 1.2.0
homepage: https://github.com/inlavigo/gg_fake_stopwatch

environment:
  sdk: ">=3.2.0 <4.0.0"

dev_dependencies:
  fake_async: ^1.3.1
  lints: ^3.0.0
  test: ^1.25.0
  flutter_lints: ^3.0.1
  pana: ^0.21.45
  args: ^2.4.2
